name: Initial Pipeline

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'
  push:

jobs:
  display-text:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "jq: $(jq --version)"
          echo "curl: $(curl --version)"
      - name: Show System Information
        run: |
          echo "Running on $(uname -s) $(uname -a)"
          echo "current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
      - name: Run a one line script
        run: echo "Hello, ${{ inputs.name }}"
      - name: show current date
        run: date
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show current branch
        run: echo "Current branch is $GITHUB_REF"
      - name: List files in the repository
        run: ls -la