name: Initial Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  display-text:
    runs-on: ubuntu-latest
    steps:
      - name: Show System Information
        run: uname -a
      - name: Print Text
        run: echo "Hello"
      - name: show current date
        run: date