name: Initial Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  display-text:
    runs-on: ubuntu-latest
    steps:
      - name: Show System Information
        run:
          echo "Running on $(uname -s) $(uname -a)"
          echo "current user: $(whoami)"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
      - name: Run a one line script
        run: echo "Hello World!"
      - name: show current date
        run: date