name: Initial Pipeline

env:
  GLOBAL_VAR: 'workflow-level'
  REPO_VAR: ${{ vars.REPO_VAR }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'
  push:

jobs:
  display-text:
    env:
      JOB_VAR: 'job-level'
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

          echo "jq: $(jq --version)"
          echo "curl: $(curl --version)"
          echo "GLOBAL_VAR: $GLOBAL_VAR"
          echo "JOB_VAR: $JOB_VAR"
        env:
          STEP_VAR: 'step-level'
        -name: Access Github repo secrets and vars
          run: |
            echo "REPO_VAR: $REPO_VAR"
            echo "REPO_SECRET: {}" ${{ secrets.REPO_SECRET }}