name: Initial Pipeline

env:
  GLOBAL_VAR: 'workflow-level'
  REPO_VAR: ${{ vars.REPO_VAR }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'
  push:

jobs:
  display-text:
    env:
      JOB_VAR: 'job-level'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Node.js version
        run: node -v